---
title: "Matemáticas 11° - Segundo Periodo 2023"
author:
- name: ICFES
  affiliation: Instituto Colombiano para la Evaluación de la Educación
date: "`r format(Sys.time(), '%d de %B de %Y')`"
output:
  pdf_document:
    latex_engine: lualatex
    toc: true
    toc_depth: '3'
    extra_dependencies: ["amssymb", "amsmath", "geometry"]
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    theme:
      version: 4
      bootswatch: flatly
    highlight: zenburn
    code_folding: show
    fig_width: 10
    fig_height: 6
    fig_caption: true
subtitle: Informe profesional de evaluación
lang: es
header-includes:
- \usepackage{amsfonts}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{float}
- \usepackage{pdflscape}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
---

```{r setup, include=FALSE}
# Configuración global del documento
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  out.width = '90%',
  cache = TRUE
)

# Cargar paquetes esenciales
library(tidyverse)
library(kableExtra)
library(ggplot2)
library(plotly)
```

# Introducción {.unnumbered}

```{r child = '01/2023-Matematicas-11-2-01.md'}
```

# Analisis de Resultados

## Competencia 1: Pensamiento Numérico
```{r child = '02/2023-Matematicas-11-2-02.md'}
```

## Competencia 2: Pensamiento Geométrico  
```{r child = '03/2023-Matematicas-11-2-03.md'}
```

## Competencia 3: Pensamiento Métrico
```{r child = '04/2023-Matematicas-11-2-04.md'}
```

## Competencia 4: Pensamiento Aleatorio
```{r child = '05/2023-Matematicas-11-2-05.md'}
```

## Competencia 5: Pensamiento Variacional
```{r child = '06/2023-Matematicas-11-2-06.md'}
```

## Competencia 6: Aplicaciones Integradas
```{r child = '07/2023-Matematicas-11-2-07.md'}
```

```{r child = '08/2023-Matematicas-11-2-08.md'}
```

```{r child = '09/2023-Matematicas-11-2-09.md'}
```

```{r child = '10/2023-Matematicas-11-2-10.md'}
```

```{r child = '11/2023-Matematicas-11-2-11.md'}
```

```{r child = '12/2023-Matematicas-11-2-12.md'}
```

```{r child = '13/2023-Matematicas-11-2-13.md'}
```

```{r child = '14/2023-Matematicas-11-2-14.md'}
```

```{r child = '15/2023-Matematicas-11-2-15.md'}
```

```{r child = '16/2023-Matematicas-11-2-16.md'}
```

```{r child = '17/2023-Matematicas-11-2-17.md'}
```

```{r child = '18/2023-Matematicas-11-2-18.md'}
```

```{r child = '19/2023-Matematicas-11-2-19.md'}
```

```{r child = '20/2023-Matematicas-11-2-20.md'}
```

# Referencias

# Referencias

::: {#refs}
:::