```{r setup, include=FALSE}
library(reticulate)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Importar el módulo Python (asegúrate de que el archivo .py esté en el mismo directorio)
source_python("boxplot_exercise.py")
```

```{python, echo=FALSE}
# Generar el ejercicio
ejercicio = generar_ejercicio()
stats = ejercicio['stats']
diagramas_ordenados = ejercicio['diagramas_ordenados']
respuesta_correcta = ejercicio['respuesta_correcta']
sol = ejercicio['sol']
```

Question
========

En una clase de antropometría, se midió la estatura (en cm) de un grupo de estudiantes. Los datos obtenidos son:

```{r, echo=FALSE}
# Mostrar tabla con datos desordenados
html_tabla = py$generar_tabla_html(py$obtener_datos_desordenados(py$stats))
cat(html_tabla)
```

¿Cuál diagrama de caja representa correctamente estos datos?

Answerlist
----------

```{r, echo=FALSE, results='asis'}
# Mostrar los diagramas como opciones
for (i in 1:4) {
  cat("- \n<br/>\n")
  diagrama_html = py$dibujar_boxplot(py$diagramas_ordenados[[i]])
  cat(diagrama_html)
  cat("\n<br/>\n")
}
```

Solution
========

```{r, echo=FALSE, results='asis'}
# Mostrar la tabla ordenada
html_tabla_ordenada = py$generar_tabla_html(py$obtener_datos_ordenados(py$stats), "Datos de estaturas ordenados")
cat(html_tabla_ordenada)
```

La opción correcta es aquella cuyo diagrama muestra exactamente estos valores:

```{r, echo=FALSE, results='asis'}
# Obtener el índice del diagrama correcto
correct_index = py$respuesta_correcta
# Mostrar el diagrama correcto
diagrama_correcto = py$dibujar_boxplot(py$diagramas_ordenados[[correct_index]])
cat(diagrama_correcto)
```

Answerlist
----------
```{r, echo=FALSE, results='asis'}
# Crear lista de respuestas (Verdadero/Falso)
respuestas = c("Falso", "Falso", "Falso", "Falso")
respuestas[py$respuesta_correcta + 1] = "Verdadero"

# Mostrar las respuestas
for (i in 1:4) {
  cat(paste("- ", respuestas[i], "\n"))
}
```

Meta-information
================
exname: Diagrama de caja para estaturas  
extype: schoice  
exsolution: `r py$sol`  
exshuffle: TRUE  