this <- normalizePath(dirname(sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)[1])))
source(file.path(this, "generador_tikz.R"))
out <- function(f) file.path(this, f)
ti <- "Informe de partidos del campeonato"; ey <- "Número de partidos"
gr <- c("Grado sexto", "Grado séptimo"); ca <- c("Partidos ganados", "Partidos perdidos"); co <- c("#F2501E", "#1EAAD8")
renderizar_tikz_png(barras_simples_tikz(c(8, 4), ca, c("#FF1A8C", "#00B33C"), "Gráfica de información del\\\\campeonato para grado séptimo", ey), out("tikz_barras_septimo.png"))
mk <- function(v) matrix(v, 2, 2, byrow = TRUE)  # filas = grupo (sexto, septimo)
renderizar_tikz_png(barras_opcion_tikz(mk(c(8,4, 5,7)), gr, ca, co, "apilada", ti, ey), out("tikz_opcion_A.png"))
renderizar_tikz_png(barras_opcion_tikz(mk(c(4,4.5, 8,5)), gr, ca, co, "apilada", ti, ey, ymax = 13), out("tikz_opcion_B.png"))
renderizar_tikz_png(barras_opcion_tikz(mk(c(5,7, 8,4)), gr, ca, co, "agrupada", ti, ey), out("tikz_opcion_C.png"))
renderizar_tikz_png(barras_opcion_tikz(mk(c(5,8, 7,4)), gr, ca, co, "agrupada", ti, ey), out("tikz_opcion_D.png"))
P <- matrix(c(3, 11, 9, 6), 2, 2, byrow = TRUE)
renderizar_tikz_png(barras_opcion_tikz(P, gr, ca, co, "agrupada", ti, ey), out("tikz_param_agrupada.png"))
renderizar_tikz_png(barras_opcion_tikz(P, gr, ca, co, "apilada", ti, ey), out("tikz_param_apilada.png"))
